NODE_ENV: "production"
NEXT_PUBLIC_MODO: "sandbox"
NEXT_PUBLIC_APP_URL: "https://printup-app-173348909763.southamerica-west1.run.app"
DB_HOST: "/cloudsql/adminsmart:southamerica-west1:printup-sql"
DB_NAME: "printup"
DB_USER: "postgres"
NEXT_PUBLIC_SUPABASE_URL: "https://zynopkkubpojllkhkfsn.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5bm9wa2t1YnBvamxsa2hrZnNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY4ODc5MzYsImV4cCI6MjA5MjQ2MzkzNn0.eomJOEbBoQLPz9RZEnzXU10XUuILKqkvriOkwdprR3A"
ADMIN_EMAIL: "guerrafelipe93@gmail.com"
FROM_EMAIL: "onboarding@resend.dev"
FROM_NAME: "PrintUp"
NOTIFY_TO: "guerrafelipe93@gmail.com"
GCS_BUCKET: "printup-archivos-sandbox"
DTE_ENABLED: "false"
